general.import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]
window.opacity = 0.8



[font]
normal = { family = "GohuFont 14 Nerd Font", style = "Regular" }

bold = { family = "GohuFont 14 Nerd Font", style = "Bold" }

italic = { family = "GohuFont 14 Nerd Font", style = "Italic" }

bold_italic = { family = "GohuFont 14 Nerd Font", style = "Bold_italic" }

size = 15




